{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Reloading __future__\n",
      "Reloading numpy\n",
      "Reloading numpy.__config__\n",
      "Reloading numpy.version\n",
      "Reloading numpy._import_tools\n",
      "Reloading os\n",
      "Reloading errno\n",
      "Reloading stat\n",
      "Reloading _stat\n",
      "Reloading posix\n",
      "Reloading posixpath\n",
      "Reloading genericpath\n",
      "Reloading _collections_abc\n",
      "Reloading abc\n",
      "Reloading _weakrefset\n",
      "Reloading _weakref\n",
      "Reloading numpy.testing\n",
      "Reloading unittest\n",
      "Reloading unittest.result\n",
      "Reloading io\n",
      "Reloading _io\n",
      "Reloading traceback\n",
      "Reloading linecache\n",
      "Reloading tokenize\n",
      "Reloading codecs\n",
      "Reloading _codecs\n",
      "Reloading collections\n",
      "Reloading _collections\n",
      "Reloading operator\n",
      "Reloading _operator\n",
      "Reloading keyword\n",
      "Reloading heapq\n",
      "Reloading itertools\n",
      "Reloading _heapq\n",
      "Reloading reprlib\n",
      "Reloading _thread\n",
      "Reloading re\n",
      "Reloading sre_compile\n",
      "Reloading _sre\n",
      "Reloading sre_parse\n",
      "Reloading sre_constants\n",
      "Reloading _locale\n",
      "Reloading copyreg\n",
      "Reloading token\n",
      "Reloading functools\n",
      "Reloading _functools\n",
      "Reloading types\n",
      "Reloading weakref\n",
      "Reloading unittest.case\n",
      "Reloading difflib\n",
      "Reloading logging\n",
      "Reloading time\n",
      "Reloading warnings\n",
      "Reloading _warnings\n",
      "Reloading string\n",
      "Reloading _string\n",
      "Reloading threading\n",
      "Reloading atexit\n",
      "Reloading pprint\n",
      "Reloading contextlib\n",
      "Reloading unittest.util\n",
      "Reloading unittest.suite\n",
      "Reloading unittest.loader\n",
      "Reloading fnmatch\n",
      "Reloading unittest.main\n",
      "Reloading argparse\n",
      "Reloading copy\n",
      "Reloading org\n",
      "Reloading textwrap\n",
      "Reloading gettext\n",
      "Reloading locale\n",
      "Reloading encodings\n",
      "Reloading encodings.aliases\n",
      "Reloading struct\n",
      "Reloading _struct\n",
      "Reloading unittest.signals\n",
      "Reloading signal\n",
      "Reloading unittest.runner\n",
      "Reloading numpy.testing.utils\n",
      "Reloading shutil\n",
      "Reloading tarfile\n",
      "Reloading grp\n",
      "Reloading pwd\n",
      "Reloading bz2\n",
      "Reloading _bz2\n",
      "Reloading tempfile\n",
      "Reloading random\n",
      "Reloading math\n",
      "Reloading hashlib\n",
      "Reloading _hashlib\n",
      "Reloading _random\n",
      "Reloading numpy.testing.nosetester\n",
      "Reloading numpy.compat\n",
      "Reloading numpy.compat._inspect\n",
      "Reloading numpy.compat.py3k\n",
      "Reloading numpy.core\n",
      "Reloading numpy.core.info\n",
      "Reloading numpy.core.numeric\n",
      "Reloading numpy.core.umath\n",
      "Reloading numpy.core.numerictypes\n",
      "Reloading numpy.core.multiarray\n",
      "Reloading numbers\n",
      "Reloading pickle\n",
      "Reloading _compat_pickle\n",
      "Reloading org\n",
      "Reloading _pickle\n",
      "Reloading numpy.core._dotblas\n",
      "Reloading numpy.core.arrayprint\n",
      "Reloading numpy.core.fromnumeric\n",
      "Reloading numpy.core.records\n",
      "Reloading numpy.core.defchararray\n",
      "Reloading numpy.core.memmap\n",
      "Reloading numpy.core.function_base\n",
      "Reloading numpy.core.machar\n",
      "Reloading numpy.core.getlimits\n",
      "Reloading numpy.core.shape_base\n",
      "Reloading numpy.lib\n",
      "Reloading numpy.lib.info\n",
      "Reloading numpy.lib.type_check\n",
      "Reloading numpy.lib.ufunclike\n",
      "Reloading numpy.lib.index_tricks\n",
      "Reloading numpy.matrixlib\n",
      "Reloading numpy.matrixlib.defmatrix\n",
      "Reloading numpy.lib.function_base\n",
      "Reloading numpy.lib.twodim_base\n",
      "Reloading numpy.lib.utils\n",
      "Reloading numpy.lib._compiled_base\n",
      "Reloading numpy.lib.stride_tricks\n",
      "Reloading numpy.lib.nanfunctions\n",
      "Reloading numpy.lib.shape_base\n",
      "Reloading numpy.lib.polynomial\n",
      "Reloading numpy.linalg\n",
      "Reloading numpy.linalg.info\n",
      "Reloading numpy.linalg.linalg\n",
      "Reloading numpy.lib.arraysetops\n",
      "Reloading numpy.lib.npyio\n",
      "Reloading numpy.lib._datasource\n",
      "Reloading numpy.lib._iotools\n",
      "Reloading numpy.lib.financial\n",
      "Reloading numpy.lib.arrayterator\n",
      "Reloading numpy.lib.arraypad\n",
      "Reloading numpy.lib._version\n",
      "Reloading pandas\n",
      "Reloading datetime\n",
      "Reloading _datetime\n",
      "Reloading distutils\n",
      "Reloading distutils.version\n",
      "Reloading pandas.version\n",
      "Reloading pandas.info\n",
      "Reloading pandas.core\n",
      "Reloading pandas.core.config_init\n",
      "Reloading pandas.core.config\n",
      "Reloading pandas.compat\n",
      "Reloading __builtin__\n",
      "Reloading http\n",
      "Reloading http.client\n",
      "Reloading email\n",
      "Reloading email.parser\n",
      "Reloading email.feedparser\n",
      "Reloading email._policybase\n",
      "Reloading email.utils\n",
      "Reloading socket\n",
      "Reloading _socket\n",
      "Reloading enum\n",
      "Reloading urllib\n",
      "Reloading urllib.parse\n",
      "Reloading email._parseaddr\n",
      "Reloading calendar\n",
      "Reloading email.charset\n",
      "Reloading email.base64mime\n",
      "Reloading base64\n",
      "Reloading binascii\n",
      "Reloading email.quoprimime\n",
      "Reloading email.encoders\n",
      "Reloading quopri\n",
      "Reloading email.message\n",
      "Reloading uu\n",
      "Reloading email._encoded_words\n",
      "Reloading email.iterators\n",
      "Reloading ssl\n",
      "Reloading _ssl\n",
      "Reloading pandas.compat.chainmap\n",
      "Reloading _abcoll\n",
      "Reloading dateutil\n",
      "Reloading pandas.core.common\n",
      "Reloading csv\n",
      "Reloading _csv\n",
      "Reloading numpy.lib.format\n",
      "Reloading pandas.algos\n",
      "Reloading pandas.lib\n",
      "Reloading pandas.tslib\n",
      "Reloading pandas.core.format\n",
      "Reloading pandas.core.base\n",
      "Reloading pandas.core.nanops\n",
      "Reloading bottleneck\n",
      "Reloading pandas.hashtable\n",
      "Reloading pandas.util\n",
      "Reloading pandas.util.decorators\n",
      "Reloading pandas.core.index\n",
      "Reloading pandas.index\n",
      "Reloading pandas.io\n",
      "Reloading pandas.io.common\n",
      "Reloading zipfile\n",
      "Reloading importlib\n",
      "Reloading _imp\n",
      "Reloading _frozen_importlib\n",
      "Reloading importlib._bootstrap\n",
      "Reloading"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR: Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "ERROR: Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 970, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 233, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 267, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/inspect.py\", line 1338, in getinnerframes\n",
      "    framelist.append((tb.tb_frame,) + getframeinfo(tb, context))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/inspect.py\", line 1302, in getframeinfo\n",
      "    lines, lnum = findsource(frame)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 171, in findsource\n",
      "    lines = linecache.getlines(file, globals_dict)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 41, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 126, in updatecache\n",
      "    with tokenize.open(fullname) as fp:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tokenize.py\", line 438, in open\n",
      "    buffer = _builtin_open(filename, 'rb')\n",
      "TypeError: open() takes 1 positional argument but 2 were given\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 126, in updatecache\n",
      "    with tokenize.open(fullname) as fp:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tokenize.py\", line 438, in open\n",
      "    buffer = _builtin_open(filename, 'rb')\n",
      "TypeError: open() takes 1 positional argument but 2 were given\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 3035, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-534e6052d72c>\", line 1, in <module>\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 341, in reload\n",
      "    return deep_reload_hook(module)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 311, in deep_reload_hook\n",
      "    newm = imp.load_module(name, fp, filename, stuff)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py\", line 235, in load_module\n",
      "    return load_source(name, filename, file)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py\", line 169, in load_source\n",
      "    module = methods.exec(sys.modules[name])\n",
      "  File \"<frozen importlib._bootstrap>\", line 1153, in exec\n",
      "  File \"<frozen importlib._bootstrap>\", line 1129, in _exec\n",
      "  File \"<frozen importlib._bootstrap>\", line 1471, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 321, in _call_with_frames_removed\n",
      "  File \"data.py\", line 4, in <module>\n",
      "    import pandas as pd\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 252, in deep_import_hook\n",
      "    head, name, buf = load_next(parent, None if level < 0 else parent, name, buf)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 156, in load_next\n",
      "    result = import_submodule(mod, subname, buf)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 201, in import_submodule\n",
      "    m = imp.load_module(fullname, fp, filename, stuff)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py\", line 245, in load_module\n",
      "    return load_package(name, filename)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py\", line 215, in load_package\n",
      "    return methods.exec(sys.modules[name])\n",
      "  File \"<frozen importlib._bootstrap>\", line 1153, in exec\n",
      "  File \"<frozen importlib._bootstrap>\", line 1129, in _exec\n",
      "  File \"<frozen importlib._bootstrap>\", line 1471, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 321, in _call_with_frames_removed\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/__init__.py\", line 47, in <module>\n",
      "    import pandas.core.config_init\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 256, in deep_import_hook\n",
      "    tail, name, buf = load_next(tail, tail, name, buf)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 156, in load_next\n",
      "    result = import_submodule(mod, subname, buf)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 201, in import_submodule\n",
      "    m = imp.load_module(fullname, fp, filename, stuff)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py\", line 235, in load_module\n",
      "    return load_source(name, filename, file)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py\", line 169, in load_source\n",
      "    module = methods.exec(sys.modules[name])\n",
      "  File \"<frozen importlib._bootstrap>\", line 1153, in exec\n",
      "  File \"<frozen importlib._bootstrap>\", line 1129, in _exec\n",
      "  File \"<frozen importlib._bootstrap>\", line 1471, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 321, in _call_with_frames_removed\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/core/config_init.py\", line 17, in <module>\n",
      "    from pandas.core.format import detect_console_encoding\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 256, in deep_import_hook\n",
      "    tail, name, buf = load_next(tail, tail, name, buf)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 156, in load_next\n",
      "    result = import_submodule(mod, subname, buf)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 201, in import_submodule\n",
      "    m = imp.load_module(fullname, fp, filename, stuff)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py\", line 235, in load_module\n",
      "    return load_source(name, filename, file)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py\", line 169, in load_source\n",
      "    module = methods.exec(sys.modules[name])\n",
      "  File \"<frozen importlib._bootstrap>\", line 1153, in exec\n",
      "  File \"<frozen importlib._bootstrap>\", line 1129, in _exec\n",
      "  File \"<frozen importlib._bootstrap>\", line 1471, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 321, in _call_with_frames_removed\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/core/format.py\", line 9, in <module>\n",
      "    from pandas.core.index import Index, MultiIndex, _ensure_index\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 256, in deep_import_hook\n",
      "    tail, name, buf = load_next(tail, tail, name, buf)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 156, in load_next\n",
      "    result = import_submodule(mod, subname, buf)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 201, in import_submodule\n",
      "    m = imp.load_module(fullname, fp, filename, stuff)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py\", line 235, in load_module\n",
      "    return load_source(name, filename, file)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py\", line 169, in load_source\n",
      "    module = methods.exec(sys.modules[name])\n",
      "  File \"<frozen importlib._bootstrap>\", line 1153, in exec\n",
      "  File \"<frozen importlib._bootstrap>\", line 1129, in _exec\n",
      "  File \"<frozen importlib._bootstrap>\", line 1471, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 321, in _call_with_frames_removed\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/core/index.py\", line 25, in <module>\n",
      "    from pandas.io.common import PerformanceWarning\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 256, in deep_import_hook\n",
      "    tail, name, buf = load_next(tail, tail, name, buf)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 156, in load_next\n",
      "    result = import_submodule(mod, subname, buf)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 201, in import_submodule\n",
      "    m = imp.load_module(fullname, fp, filename, stuff)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py\", line 235, in load_module\n",
      "    return load_source(name, filename, file)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py\", line 169, in load_source\n",
      "    module = methods.exec(sys.modules[name])\n",
      "  File \"<frozen importlib._bootstrap>\", line 1153, in exec\n",
      "  File \"<frozen importlib._bootstrap>\", line 1129, in _exec\n",
      "  File \"<frozen importlib._bootstrap>\", line 1471, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 321, in _call_with_frames_removed\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/io/common.py\", line 5, in <module>\n",
      "    import zipfile\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 252, in deep_import_hook\n",
      "    head, name, buf = load_next(parent, None if level < 0 else parent, name, buf)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 156, in load_next\n",
      "    result = import_submodule(mod, subname, buf)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 201, in import_submodule\n",
      "    m = imp.load_module(fullname, fp, filename, stuff)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py\", line 235, in load_module\n",
      "    return load_source(name, filename, file)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py\", line 169, in load_source\n",
      "    module = methods.exec(sys.modules[name])\n",
      "  File \"<frozen importlib._bootstrap>\", line 1153, in exec\n",
      "  File \"<frozen importlib._bootstrap>\", line 1129, in _exec\n",
      "  File \"<frozen importlib._bootstrap>\", line 1471, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 321, in _call_with_frames_removed\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/zipfile.py\", line 9, in <module>\n",
      "    import importlib.util\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 256, in deep_import_hook\n",
      "    tail, name, buf = load_next(tail, tail, name, buf)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 156, in load_next\n",
      "    result = import_submodule(mod, subname, buf)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 201, in import_submodule\n",
      "    m = imp.load_module(fullname, fp, filename, stuff)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py\", line 235, in load_module\n",
      "    return load_source(name, filename, file)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py\", line 169, in load_source\n",
      "    module = methods.exec(sys.modules[name])\n",
      "  File \"<frozen importlib._bootstrap>\", line 1153, in exec\n",
      "  File \"<frozen importlib._bootstrap>\", line 1129, in _exec\n",
      "  File \"<frozen importlib._bootstrap>\", line 1471, in exec_module\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/_bootstrap.py\", line 321, in _call_with_frames_removed\n",
      "    return f(*args, **kwds)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/importlib/util.py\", line 3, in <module>\n",
      "    from ._bootstrap import MAGIC_NUMBER\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 252, in deep_import_hook\n",
      "    head, name, buf = load_next(parent, None if level < 0 else parent, name, buf)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 156, in load_next\n",
      "    result = import_submodule(mod, subname, buf)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/lib/deepreload.py\", line 196, in import_submodule\n",
      "    fp, filename, stuff = imp.find_module(subname, path)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py\", line 271, in find_module\n",
      "    \"not {}\".format(type(name)))\n",
      "RuntimeError: 'list' must be None or a list, not <class 'str'>\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 1848, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'RuntimeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 970, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 233, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 267, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/inspect.py\", line 1338, in getinnerframes\n",
      "    framelist.append((tb.tb_frame,) + getframeinfo(tb, context))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/inspect.py\", line 1302, in getframeinfo\n",
      "    lines, lnum = findsource(frame)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 171, in findsource\n",
      "    lines = linecache.getlines(file, globals_dict)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 41, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 126, in updatecache\n",
      "    with tokenize.open(fullname) as fp:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tokenize.py\", line 438, in open\n",
      "    buffer = _builtin_open(filename, 'rb')\n",
      "TypeError: open() takes 1 positional argument but 2 were given\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 2981, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 3052, in run_code\n",
      "    self.showtraceback()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 1851, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 1240, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 1148, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 1000, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 949, in format_exception_as_a_whole\n",
      "    records = self.get_records(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 979, in get_records\n",
      "    traceback.print_exc(file=self.ostream)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 252, in print_exc\n",
      "    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 169, in print_exception\n",
      "    for line in _format_exception_iter(etype, value, tb, limit, chain):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 153, in _format_exception_iter\n",
      "    yield from _format_list_iter(_extract_tb_iter(tb, limit=limit))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 18, in _format_list_iter\n",
      "    for filename, lineno, name, line in extracted_list:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 65, in _extract_tb_or_stack_iter\n",
      "    line = linecache.getline(filename, lineno, f.f_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 15, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 41, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 126, in updatecache\n",
      "    with tokenize.open(fullname) as fp:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tokenize.py\", line 438, in open\n",
      "    buffer = _builtin_open(filename, 'rb')\n",
      "TypeError: open() takes 1 positional argument but 2 were given\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 1848, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 970, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 233, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 267, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/inspect.py\", line 1338, in getinnerframes\n",
      "    framelist.append((tb.tb_frame,) + getframeinfo(tb, context))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/inspect.py\", line 1302, in getframeinfo\n",
      "    lines, lnum = findsource(frame)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 171, in findsource\n",
      "    lines = linecache.getlines(file, globals_dict)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 41, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 126, in updatecache\n",
      "    with tokenize.open(fullname) as fp:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tokenize.py\", line 438, in open\n",
      "    buffer = _builtin_open(filename, 'rb')\n",
      "TypeError: open() takes 1 positional argument but 2 were given\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/kernel/zmq/ipkernel.py\", line 181, in do_execute\n",
      "    shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 2871, in run_cell\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 3000, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/interactiveshell.py\", line 1851, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 1240, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 1148, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 1000, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 949, in format_exception_as_a_whole\n",
      "    records = self.get_records(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/ultratb.py\", line 979, in get_records\n",
      "    traceback.print_exc(file=self.ostream)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 252, in print_exc\n",
      "    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 169, in print_exception\n",
      "    for line in _format_exception_iter(etype, value, tb, limit, chain):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 153, in _format_exception_iter\n",
      "    yield from _format_list_iter(_extract_tb_iter(tb, limit=limit))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 18, in _format_list_iter\n",
      "    for filename, lineno, name, line in extracted_list:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 65, in _extract_tb_or_stack_iter\n",
      "    line = linecache.getline(filename, lineno, f.f_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 15, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 41, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 126, in updatecache\n",
      "    with tokenize.open(fullname) as fp:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tokenize.py\", line 438, in open\n",
      "    buffer = _builtin_open(filename, 'rb')\n",
      "TypeError: open() takes 1 positional argument but 2 were given\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/kernel/zmq/kernelbase.py\", line 213, in dispatch_shell\n",
      "    handler(stream, idents, msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/kernel/zmq/kernelbase.py\", line 362, in execute_request\n",
      "    user_expressions, allow_stdin)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/kernel/zmq/ipkernel.py\", line 191, in do_execute\n",
      "    tb_list = traceback.format_exception(etype, evalue, tb)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 181, in format_exception\n",
      "    return list(_format_exception_iter(etype, value, tb, limit, chain))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 153, in _format_exception_iter\n",
      "    yield from _format_list_iter(_extract_tb_iter(tb, limit=limit))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 18, in _format_list_iter\n",
      "    for filename, lineno, name, line in extracted_list:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 65, in _extract_tb_or_stack_iter\n",
      "    line = linecache.getline(filename, lineno, f.f_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 15, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 41, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 126, in updatecache\n",
      "    with tokenize.open(fullname) as fp:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tokenize.py\", line 438, in open\n",
      "    buffer = _builtin_open(filename, 'rb')\n",
      "TypeError: open() takes 1 positional argument but 2 were given\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 978, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 828, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/config/application.py\", line 104, in format\n",
      "    return super(LevelFormatter, self).format(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 573, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 523, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 169, in print_exception\n",
      "    for line in _format_exception_iter(etype, value, tb, limit, chain):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 153, in _format_exception_iter\n",
      "    yield from _format_list_iter(_extract_tb_iter(tb, limit=limit))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 18, in _format_list_iter\n",
      "    for filename, lineno, name, line in extracted_list:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 65, in _extract_tb_or_stack_iter\n",
      "    line = linecache.getline(filename, lineno, f.f_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 15, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 41, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 126, in updatecache\n",
      "    with tokenize.open(fullname) as fp:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tokenize.py\", line 438, in open\n",
      "    buffer = _builtin_open(filename, 'rb')\n",
      "TypeError: open() takes 1 positional argument but 2 were given\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zmq/eventloop/zmqstream.py\", line 407, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tornado/stack_context.py\", line 275, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/kernel/zmq/kernelbase.py\", line 252, in dispatcher\n",
      "    return self.dispatch_shell(stream, msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/kernel/zmq/kernelbase.py\", line 215, in dispatch_shell\n",
      "    self.log.error(\"Exception in message handler:\", exc_info=True)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 1303, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 1409, in _log\n",
      "    self.handle(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 1419, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 1481, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 853, in handle\n",
      "    self.emit(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 984, in emit\n",
      "    self.handleError(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 906, in handleError\n",
      "    traceback.print_exception(t, v, tb, None, sys.stderr)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 169, in print_exception\n",
      "    for line in _format_exception_iter(etype, value, tb, limit, chain):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 153, in _format_exception_iter\n",
      "    yield from _format_list_iter(_extract_tb_iter(tb, limit=limit))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 18, in _format_list_iter\n",
      "    for filename, lineno, name, line in extracted_list:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 65, in _extract_tb_or_stack_iter\n",
      "    line = linecache.getline(filename, lineno, f.f_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 15, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 41, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 126, in updatecache\n",
      "    with tokenize.open(fullname) as fp:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tokenize.py\", line 438, in open\n",
      "    buffer = _builtin_open(filename, 'rb')\n",
      "TypeError: open() takes 1 positional argument but 2 were given\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 978, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 828, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 573, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 523, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 169, in print_exception\n",
      "    for line in _format_exception_iter(etype, value, tb, limit, chain):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 153, in _format_exception_iter\n",
      "    yield from _format_list_iter(_extract_tb_iter(tb, limit=limit))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 18, in _format_list_iter\n",
      "    for filename, lineno, name, line in extracted_list:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 65, in _extract_tb_or_stack_iter\n",
      "    line = linecache.getline(filename, lineno, f.f_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 15, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 41, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 126, in updatecache\n",
      "    with tokenize.open(fullname) as fp:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tokenize.py\", line 438, in open\n",
      "    buffer = _builtin_open(filename, 'rb')\n",
      "TypeError: open() takes 1 positional argument but 2 were given\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tornado/ioloop.py\", line 568, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tornado/stack_context.py\", line 275, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/kernel/zmq/kernelbase.py\", line 234, in enter_eventloop\n",
      "    self.eventloop(self)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/kernel/zmq/eventloops.py\", line 251, in loop_cocoa\n",
      "    kernel.do_one_iteration()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/kernel/zmq/kernelbase.py\", line 267, in do_one_iteration\n",
      "    stream.flush(zmq.POLLIN, 1)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zmq/eventloop/zmqstream.py\", line 345, in flush\n",
      "    self._handle_recv()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zmq/eventloop/zmqstream.py\", line 465, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zmq/eventloop/zmqstream.py\", line 410, in _run_callback\n",
      "    exc_info=True)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 1303, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 1409, in _log\n",
      "    self.handle(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 1419, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 1481, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 853, in handle\n",
      "    self.emit(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 984, in emit\n",
      "    self.handleError(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 906, in handleError\n",
      "    traceback.print_exception(t, v, tb, None, sys.stderr)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 169, in print_exception\n",
      "    for line in _format_exception_iter(etype, value, tb, limit, chain):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 153, in _format_exception_iter\n",
      "    yield from _format_list_iter(_extract_tb_iter(tb, limit=limit))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 18, in _format_list_iter\n",
      "    for filename, lineno, name, line in extracted_list:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 65, in _extract_tb_or_stack_iter\n",
      "    line = linecache.getline(filename, lineno, f.f_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 15, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 41, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 126, in updatecache\n",
      "    with tokenize.open(fullname) as fp:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tokenize.py\", line 438, in open\n",
      "    buffer = _builtin_open(filename, 'rb')\n",
      "TypeError: open() takes 1 positional argument but 2 were given\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 978, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 828, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 573, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 523, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 169, in print_exception\n",
      "    for line in _format_exception_iter(etype, value, tb, limit, chain):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 153, in _format_exception_iter\n",
      "    yield from _format_list_iter(_extract_tb_iter(tb, limit=limit))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 18, in _format_list_iter\n",
      "    for filename, lineno, name, line in extracted_list:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 65, in _extract_tb_or_stack_iter\n",
      "    line = linecache.getline(filename, lineno, f.f_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 15, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 41, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 126, in updatecache\n",
      "    with tokenize.open(fullname) as fp:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tokenize.py\", line 438, in open\n",
      "    buffer = _builtin_open(filename, 'rb')\n",
      "TypeError: open() takes 1 positional argument but 2 were given\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py\", line 170, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/kernel/__main__.py\", line 3, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/config/application.py\", line 574, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/kernel/zmq/kernelapp.py\", line 373, in start\n",
      "    ioloop.IOLoop.instance().start()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zmq/eventloop/ioloop.py\", line 151, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tornado/ioloop.py\", line 784, in start\n",
      "    self._run_callback(callback)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tornado/ioloop.py\", line 576, in _run_callback\n",
      "    self.handle_callback_exception(callback)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tornado/ioloop.py\", line 588, in handle_callback_exception\n",
      "    app_log.error(\"Exception in callback %r\", callback, exc_info=True)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 1303, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 1409, in _log\n",
      "    self.handle(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 1419, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 1481, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 853, in handle\n",
      "    self.emit(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 984, in emit\n",
      "    self.handleError(record)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/logging/__init__.py\", line 906, in handleError\n",
      "    traceback.print_exception(t, v, tb, None, sys.stderr)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 169, in print_exception\n",
      "    for line in _format_exception_iter(etype, value, tb, limit, chain):\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 153, in _format_exception_iter\n",
      "    yield from _format_list_iter(_extract_tb_iter(tb, limit=limit))\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 18, in _format_list_iter\n",
      "    for filename, lineno, name, line in extracted_list:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/traceback.py\", line 65, in _extract_tb_or_stack_iter\n",
      "    line = linecache.getline(filename, lineno, f.f_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 15, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 41, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/linecache.py\", line 126, in updatecache\n",
      "    with tokenize.open(fullname) as fp:\n",
      "  File \"/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tokenize.py\", line 438, in open\n",
      "    buffer = _builtin_open(filename, 'rb')\n",
      "TypeError: open() takes 1 positional argument but 2 were given\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " importlib.util\n",
      "Reloading importlib.util._bootstrap\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n"
     ]
    }
   ],
   "source": [
    "dreload(data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Extracting features for UVA\n",
      "-- missing 2/1010 feature values for Volume\n",
      "-- missing 1/1010 feature values for Embo\n",
      "Sex                             int64\n",
      "Age                           float64\n",
      "SM_Vein                         int64\n",
      "Max_Diameter                  float64\n",
      "Volume                        float64\n",
      "History_of_Hemorrhage           int64\n",
      "Embo                          float64\n",
      "Aneurysm                      float64\n",
      "Max_Dose                      float64\n",
      "Marginal_Dose                 float64\n",
      "Isodose                       float64\n",
      "Shots                         float64\n",
      "Surgery                          bool\n",
      "Location_frontal                 bool\n",
      "Location_2                       bool\n",
      "Location_3                       bool\n",
      "Location_4                       bool\n",
      "Location_5                       bool\n",
      "Location_6                       bool\n",
      "Location_7                       bool\n",
      "Location_8                       bool\n",
      "Location_9                       bool\n",
      "Marginal_Dose_times_Volume    float64\n",
      "Marginal_Dose_times_area      float64\n",
      "dtype: object\n",
      "-- Row-wise feature mask len=1010, type=<class 'numpy.ndarray'>, dtype=bool, sum=1007\n",
      "# censored at 4.000000 years: 100 / 1010\n",
      "-- Followup mask len=1010, type=<class 'numpy.ndarray'>, dtype=bool, sum=910\n",
      "-- Total patients=1010, Complete patient rows=1007, Patients with sufficient followup=910, Dataset size=907\n",
      "X (907, 24) float64\n",
      "oblit (907,) bool\n",
      "H 76\n",
      "RIC 365\n",
      "RIC Permanet 26\n",
      "Extracting features for PA\n",
      "-- missing 2/800 feature values for Aneurysm\n",
      "-- missing 7/800 feature values for Shots\n",
      "Sex                             int64\n",
      "Age                           float64\n",
      "SM_Vein                         int64\n",
      "Max_Diameter                  float64\n",
      "Volume                        float64\n",
      "History_of_Hemorrhage           int64\n",
      "Embo                          float64\n",
      "Aneurysm                      float64\n",
      "Max_Dose                      float64\n",
      "Marginal_Dose                 float64\n",
      "Isodose                       float64\n",
      "Shots                         float64\n",
      "Surgery                          bool\n",
      "Location_frontal                 bool\n",
      "Location_2                       bool\n",
      "Location_3                       bool\n",
      "Location_4                       bool\n",
      "Location_5                       bool\n",
      "Location_6                       bool\n",
      "Location_7                       bool\n",
      "Location_8                       bool\n",
      "Location_9                       bool\n",
      "Marginal_Dose_times_Volume    float64\n",
      "Marginal_Dose_times_area      float64\n",
      "dtype: object\n",
      "-- Row-wise feature mask len=800, type=<class 'numpy.ndarray'>, dtype=bool, sum=793\n",
      "# censored at 4.000000 years: 259 / 800\n",
      "-- Followup mask len=800, type=<class 'numpy.ndarray'>, dtype=bool, sum=541\n",
      "-- Total patients=800, Complete patient rows=793, Patients with sufficient followup=541, Dataset size=535\n",
      "X (535, 24) float64\n",
      "oblit (535,) bool\n",
      "H 64\n",
      "RIC 124\n",
      "RIC Permanet 13\n"
     ]
    }
   ],
   "source": [
    "import data\n",
    "datasets, df = data.load_datasets()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "X_pa, Y_pa, _, _, df_pa = datasets['pa'] \n",
    "X_uva, Y_uva, _, _, df_uva = datasets['uva']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Sex                             1.000000\n",
       "Age                             5.041997\n",
       "SM_Vein                         1.000000\n",
       "Max_Diameter                   22.000000\n",
       "Volume                          2.760000\n",
       "History_of_Hemorrhage           1.000000\n",
       "Embo                            0.000000\n",
       "Aneurysm                        0.000000\n",
       "Max_Dose                       40.000000\n",
       "Marginal_Dose                  22.000000\n",
       "Isodose                        50.000000\n",
       "Shots                           2.000000\n",
       "Surgery                         0.000000\n",
       "Location_frontal                0.000000\n",
       "Location_2                      0.000000\n",
       "Location_3                      0.000000\n",
       "Location_4                      0.000000\n",
       "Location_5                      0.000000\n",
       "Location_6                      0.000000\n",
       "Location_7                      0.000000\n",
       "Location_8                      0.000000\n",
       "Location_9                      0.000000\n",
       "Marginal_Dose_times_Volume     58.000000\n",
       "Marginal_Dose_times_area      199.382080\n",
       "dtype: float64"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_uva.median(axis=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0.58878504672897192"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import sklearn.linear_model\n",
    "rf = sklearn.ensemble.RandomForestClassifier(n_estimators=200)\n",
    "rf.fit(X_uva, Y_uva)\n",
    "Y_prob = rf.predict_proba(X_pa)\n",
    "Y_pred = rf.predict(X_pa)\n",
    "np.mean(Y_pred == Y_pa)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.collections.PolyCollection at 0x10a7b83c8>"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import seaborn;\n",
    "seaborn.plt.hexbin(df_pa.Isodose, df_pa.Marginal_Dose, gridsize=20)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "X_pa, Y_pa, df_pa = datasets['pa'][:3]\n",
    "X_uva, Y_uva, df_uva = datasets['uva'][:3]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "'Series' object has no attribute 'columns'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-14-3712cb830e1e>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mdf_pa\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcolumns\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandas/core/generic.py\u001b[0m in \u001b[0;36m__getattr__\u001b[0;34m(self, name)\u001b[0m\n\u001b[1;32m   1971\u001b[0m                 \u001b[0;32mor\u001b[0m \u001b[0mname\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_metadata\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1972\u001b[0m                 or name in self._accessors):\n\u001b[0;32m-> 1973\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mobject\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__getattribute__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1974\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1975\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mname\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_info_axis\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'Series' object has no attribute 'columns'"
     ]
    }
   ],
   "source": [
    "df_pa.columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "candidate_models = {}\n",
    "Cs = [10.0 ** -6, 10.0 ** -5, 0.0001, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10]\n",
    "lr_parameter_grids = [\n",
    "    {\n",
    "         'penalty' : ['l1', 'l2'],\n",
    "         'fit_intercept' : [True, False],\n",
    "         'C' : Cs, \n",
    "    }\n",
    "]\n",
    "lr = sklearn.linear_model.LogisticRegression()\n",
    "candidate_models[lr] = lr_parameter_grids\n",
    "\n",
    "rf_parameter_grids = [\n",
    "    {\n",
    "        'min_samples_split' : [1, 2, 4, 8],\n",
    "        'max_depth' : [10, 20, 30, None],\n",
    "        'n_estimators' : [25, 50, 100, 200, 300],\n",
    "     }\n",
    "]\n",
    "rf = sklearn.ensemble.RandomForestClassifier()\n",
    "candidate_models[rf] = rf_parameter_grids"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'datasets' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-2-75df135d8ad1>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mX_uva\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mY_uva\u001b[0m  \u001b[0;34m=\u001b[0m \u001b[0mdatasets\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'uva'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0mX_pa\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mY_pa\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdatasets\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'pa'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;36m2\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0mX_combined\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mnp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mvstack\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mX_uva\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mX_pa\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mY_combined\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mnp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mhstack\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mY_uva\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mY_pa\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'datasets' is not defined"
     ]
    }
   ],
   "source": [
    "X_uva, Y_uva  = datasets['uva'][:2]\n",
    "X_pa, Y_pa = datasets['pa'][:2]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "import cv\n",
    "reload(cv)\n",
    "best_model, params, auc = cv.find_best_model(\n",
    "  X_combined,\n",
    "  Y_combined,\n",
    "  # sklearn.linear_model.LogisticRegression, lr_parameter_grids\n",
    "  sklearn.ensemble.RandomForestClassifier, \n",
    "  rf_parameter_grids, \n",
    "  target_value=2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "best_model, params, auc"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "lr = sklearn.linear_model.LogisticRegression(C=0.1, penalty='l1'); \n",
    "m = X_train.mean(axis=0)\n",
    "X_train_normalized = X_train - m\n",
    "s = X_train_normalized.std(axis=0)\n",
    "s[s==0] = 1\n",
    "X_train_normalized /= s\n",
    "lr.fit(X_train_normalized, Y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "pred = lr.predict(X_train_normalized)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "(pred == Y_train).mean()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "_, idx = np.where(lr.coef_ != 0) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "df_uva = datasets['uva'][-1]\n",
    "uva_features = list(df_uva.columns)\n",
    "[uva_features[i] for i in set(idx)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "cv.roc_auc_score(Y_test, Y_pred[:, -1])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "params"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "best_model.model.coef_"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "[datasets['features'][i] for (i, x) in enumerate(best_model.model.coef_.ravel()) if abs(x) > 0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'best_model' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-3-b964832987f8>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mbest_model\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m: name 'best_model' is not defined"
     ]
    }
   ],
   "source": [
    "best_model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.4.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
